### ISSUE TITLE
スクリプトとRocco di Forteさんのツールについて

### ISSUE THREAD

**Issue by ShiraGawaAnri** [refis/ScriptDustbox#1]
どうも、はじめまして
ラグナロクサーバー作りに興味持ちものです。
Rocco di Forteさんの
NPC調査用パケットキャプチャ
というツールのリンクがとっくに切れてしまいましたので、
そちらからいただけますでしょうか。
感謝いたしましす。
また、ティアマットメモリーについても興味深いです、もしよろしければ
ご検討はいかがでしょうか、
もちろんただとは言いませんから、ぜひよろしくおねがいします。
もし何か気に障ることがありましたら、お詫び申し上げます。

**Comment by refis** [comment]
NPC調査用パケットキャプチャにつきまして、
オリジナルと思われるファイルをアップロードしましたので
確認してみてください。

**Comment by ShiraGawaAnri** [comment]
> NPC調査用パケットキャプチャにつきまして、
> オリジナルと思われるファイルをアップロードしましたので
> 確認してみてください。

返事ありがとうございした。では、いただきます。
